[versions]
compileSdk = "33"
minSdk = "29"
targetSdk = "33"
hilt = "2.44"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version = "1.7.0"}
androidx-appcompat = { module = "androidx.appcompat:appcompat", version = "1.6.1"}
android-material = { module = "com.google.android.material:material", version = "1.8.0"}
junit-junit = { module = "junit:junit", version = "4.13.2"}
androidx-test-unit = { module = "androidx.test.ext:junit", version = "1.1.5"}
androidx-test-espresso = { module = "androidx.test.espresso:espresso-core", version = "3.5.1"}
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version = "2.1.4"}
androidx-fragment-ktx = { module = "androidx.fragment:fragment-ktx", version = "1.5.6" }

hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "hilt"}
hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt"}

okhttp-bom = "com.squareup.okhttp3:okhttp-bom:4.10.0"
okhttp = { module = "com.squareup.okhttp3:okhttp" }
okhttp-sse = { module = "com.squareup.okhttp3:okhttp-sse" }

gson = { module = "com.google.code.gson:gson", version = "2.10.1"}